version: '3.7'

services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: redpanda
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:29092,external://0.0.0.0:9092
      - --advertise-kafka-addr internal://redpanda:29092,external://localhost:9092
      - --pandaproxy-addr internal://0.0.0.0:28082,external://0.0.0.0:8082
      - --advertise-pandaproxy-addr internal://redpanda:28082,external://localhost:8082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:8081
      - --rpc-addr redpanda:33145
      - --advertise-rpc-addr redpanda:33145
      - --mode dev-container
      - --smp 1
      - --memory 1G
    ports:
      - 8081:8081
      - 8082:8082
      - 9092:9092
      - 29092:29092
      - 9644:9644
    volumes:
      - redpanda-data:/var/lib/redpanda/data
    networks:
      - streaming_network
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health"]
      interval: 10s
      timeout: 3s
      retries: 5

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda-console
    environment:
      KAFKA_BROKERS: redpanda:29092
      KAFKA_SCHEMAREGISTRY_ENABLED: "true"
      KAFKA_SCHEMAREGISTRY_URLS: http://redpanda:8081
      REDPANDA_ADMINAPI_ENABLED: "true"
      REDPANDA_ADMINAPI_URLS: http://redpanda:9644
    ports:
      - 8086:8080
    networks:
      - streaming_network
    depends_on:
      - redpanda

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - 8123:8123
      - 9000:9000
    volumes:
      - ./docker/clickhouse-init:/docker-entrypoint-initdb.d
      - clickhouse-data:/var/lib/clickhouse
    networks:
      - streaming_network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  streaming_network:
    driver: bridge

volumes:
  redpanda-data:
  clickhouse-data:
